CREATE TABLE GROUP_2401232 (
    GRP_SK INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100),
    GROUP_ID VARCHAR(8) NOT NULL,
    GROUP_NAME VARCHAR(30) NOT NULL,
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    STREET VARCHAR(35),
    CITY VARCHAR(15),
    STATE VARCHAR(20),
    ZIP NUMBER(5)  NOT NULL
) PRIMARY INDEX (GROUP_ID);

CREATE TABLE SUBGRP_2401232 (
    SUBGRP_SK INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE),
    SUBGRP_ID VARCHAR(10) NOT NULL,
    GROUP_ID VARCHAR(10) NOT NULL,
    SUBGRP_NAME VARCHAR(100),
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    PRIMARY KEY (SUBGRP_ID, GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_2401232(GROUP_ID)
);
);

CREATE TABLE SUBSCRIBER_2401232 (
    SUB_SK INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100),
    SUB_ID VARCHAR(9) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    BIRTH_DT DATE NOT NULL,
    SUBGRP_ID VARCHAR(4) NOT NULL,
    GRP_ID VARCHAR(8) NOT NULL,
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    ELIG_IND VARCHAR(1) NOT NULL,
    FOREIGN KEY (SUBGRP_ID) REFERENCES SUBGRP_2401232(SUBGRP_ID),
    FOREIGN KEY (GRP_ID) REFERENCES GROUP_2401232(GROUP_ID)

) UNIQUE PRIMARY INDEX (SUB_ID);
