CREATE TABLE HEALTH_CARE.GROUP_TABLE (
    GRP_SK NUMBER(10) AUTO_INCREMENT,
    GROUP_ID VARCHAR2(8) NOT NULL,
    GROUP_NAME VARCHAR2(30)  NOT NULL,
    EFF_DT DATE  NOT NULL,
    TERM_DT DATE  NOT NULL,
    STREET VARCHAR2(35),
    CITY VARCHAR2(15),
    STATE VARCHAR2(20),
    ZIP NUMBER(5)  NOT NULL
) PRIMARY INDEX (GROUP_ID);

CREATE TABLE HEALTH_CARE.SUBGRP_TABLE (
    SUBGRP_SK NUMBER(10) AUTO_INCREMENT NOT NULL,
    SUBGRP_ID VARCHAR2(4) NOT NULL,
    SUBGRP_NAME VARCHAR2(30) NOT NULL,
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    GROUP_ID VARCHAR2(8) NOT NULL
);

CREATE TABLE HEALTH_CARE.SUBSCRIBER_TABLE (
    SUB_SK NUMBER(10) AUTO_INCREMENT NOT NULL,
    SUB_ID VARCHAR2(9)  NOT NULL,
    FIRST_NAME VARCHAR2(30)  NOT NULL,
    LAST_NAME VARCHAR2(30)  NOT NULL,
    GENDER VARCHAR2(1)  NOT NULL,
    BIRTH_DT DATE  NOT NULL,
    SUBGRP_ID VARCHAR2(4)  NOT NULL,
    GRP_ID VARCHAR2(8)  NOT NULL,
    EFF_DT DATE  NOT NULL,
    TERM_DT DATE  NOT NULL,
    ELIG_IND VARCHAR2(1)  NOT NULL
) UNIQUE PRIMARY INDEX (SUB_ID);
