
-- Teradata SQL Script for Health Care System Schema

CREATE TABLE GROUP_TABLE (
    GRP_SK INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE),
    GROUP_ID VARCHAR(10) NOT NULL,
    GROUP_NAME VARCHAR(100),
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    PRIMARY KEY (GROUP_ID)
);

CREATE TABLE SUBGRP_TABLE (
    SUBGRP_SK INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE),
    SUBGRP_ID VARCHAR(10) NOT NULL,
    GROUP_ID VARCHAR(10) NOT NULL,
    SUBGRP_NAME VARCHAR(100),
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    PRIMARY KEY (SUBGRP_ID, GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID)
);

CREATE TABLE SUBSCRIBER_TABLE (
    SUB_SK INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE),
    SUB_ID VARCHAR(15) NOT NULL,
    GROUP_ID VARCHAR(10) NOT NULL,
    SUBGRP_ID VARCHAR(10) NOT NULL,
    FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    DOB DATE,
    GENDER CHAR(1),
    EFF_DT DATE NOT NULL,
    TERM_DT DATE NOT NULL,
    ELIG_IND CHAR(1) NOT NULL,
    PRIMARY KEY (SUB_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID),
    FOREIGN KEY (SUBGRP_ID, GROUP_ID) REFERENCES SUBGRP_TABLE(SUBGRP_ID, GROUP_ID)
);

CREATE TABLE SUBSCRIBER_TABLE (
    SUB_SK INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SUB_ID VARCHAR(10) NOT NULL,
    GROUP_ID VARCHAR(10) NOT NULL,
    SUBGRP_ID VARCHAR(10) NOT NULL,
    SUB_NAME VARCHAR(100),
    DOB DATE,
    GENDER CHAR(1),
    ELIG_IND CHAR(1),
    EFF_DT DATE,
    TERM_DT DATE,
    PRIMARY KEY (SUB_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID),
    FOREIGN KEY (SUBGRP_ID, GROUP_ID) REFERENCES SUBGRP_TABLE(SUBGRP_ID, GROUP_ID)
);
