-- Create GROUP_TABLE with GROUP_ID as primary key
CREATE TABLE GROUP_TABLE (
    GROUP_ID VARCHAR(10) PRIMARY KEY,
    GROUP_NAME VARCHAR(100),
    EFF_DT DATE,
    TERM_DT DATE
);

-- Create SUBGRP_TABLE with composite primary key and foreign key to GROUP_TABLE
CREATE TABLE SUBGRP_TABLE (
    SUBGRP_ID VARCHAR(10),
    GROUP_ID VARCHAR(10),
    SUBGRP_NAME VARCHAR(100),
    EFF_DT DATE,
    TERM_DT DATE,
    PRIMARY KEY (SUBGRP_ID, GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID)
);

-- Create SUBSCRIBER_TABLE with foreign keys to GROUP_TABLE and SUBGRP_TABLE
CREATE TABLE SUBSCRIBER_TABLE (
    SUB_ID VARCHAR(10) PRIMARY KEY,
    GROUP_ID VARCHAR(10),
    SUBGRP_ID VARCHAR(10),
    SUBSCRIBER_NAME VARCHAR(100),
    ELIG_IND CHAR(1),
    EFF_DT DATE,
    TERM_DT DATE,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TABLE(GROUP_ID),
    FOREIGN KEY (SUBGRP_ID, GROUP_ID) REFERENCES SUBGRP_TABLE(SUBGRP_ID, GROUP_ID)
);
